export const Strings = {
  brand: {
    system: 'سامانه ۱۳۷',
    city: 'ارجاع خودرو',
    municipality: 'شهرداری سبزوار',
  },

  splashAccessibility: 'صفحه شروع نرم‌افزار ارجاع خودرو ۱۳۷',
  logoAccessibility: 'لوگوی سامانه',

  common: {
    back: 'بازگشت',
    error: 'خطا',
    save: 'ذخیره',
    cancel: 'انصراف',
    confirm: 'تأیید',
    optional: 'اختیاری',
    required: 'الزامی',
  },

  login: {
    title: 'ورود به سامانه',
    subtitle: 'کد ملی خود را وارد کنید',
    button: 'ادامه',
    ssoHint: 'در صورت نبود حساب، به سامانه وزارت کشور هدایت می‌شوید',
    loading: 'در حال بررسی...',
    melliPlaceholder: 'کد ملی ۱۰ رقمی',
    melliRequired: 'کد ملی را وارد کنید',
    melliInvalid: 'کد ملی باید ۱۰ رقم باشد',
    selectPhoneTitle: 'انتخاب شماره موبایل',
    selectPhoneSubtitle: 'شماره‌ای که کد تایید به آن ارسال شود را انتخاب کنید',
    sendOtp: 'ارسال کد تایید',
    otpTitle: 'کد تایید',
    otpSubtitle: 'کد ارسال‌شده به شماره زیر را وارد کنید',
    otpPlaceholder: 'کد ۵ رقمی',
    otpRequired: 'کد تایید را وارد کنید',
    verifyOtp: 'تایید و ورود',
    resendOtp: 'ارسال مجدد کد',
    moiButton: 'ورود با پنجره ملی خدمات',
    moiLoading: 'در حال انتقال به وزارت کشور...',
  },

  home: {
    requests: 'درخواست‌های ارجاع‌شده',
    empty: 'درخواستی برای این خودرو وجود ندارد',
    profileAccessibility: 'پروفایل کاربر',
    notificationsAccessibility: 'اعلان‌ها',
    openRequestsAccessibility: 'درخواست‌های باز',
    speedAlertAccessibility: 'هشدار سرعت غیرمجاز',
    settingsAccessibility: 'تنظیمات نرم‌افزار',
    newRequest: 'درخواست جدید',
    radiusHint: 'فقط درخواست‌های داخل محدوده پلیگانی منطقه این خودرو نمایش داده می‌شود',
  },

  settings: {
    title: 'تنظیمات تبلت و خودرو',
    maxSpeed: 'سرعت مجاز (کیلومتر بر ساعت)',
    allowNew: 'دریافت درخواست جدید در زمان وجود درخواست باز',
    allowNewHint:
      'در صورت غیرفعال بودن، تا تعیین تکلیف درخواست فعال، درخواست جدید پذیرفته نمی‌شود.',
    region: 'منطقه عملیاتی خودرو',
    regionHint: 'خودرو فقط درخواست‌های داخل پلیگان همین منطقه را می‌بیند.',
    vehicleSection: 'مشخصات خودرو',
    plate: 'پلاک',
    code: 'شماره / کد خودرو',
    type: 'نوع خودرو',
    model: 'مدل',
    titleField: 'عنوان خودرو',
    unit: 'واحد یا گروه سازمانی',
    saved: 'تنظیمات ذخیره شد',
    onlyAdmin: 'فقط کاربر مدیر به این بخش دسترسی دارد.',
  },

  requestDetail: {
    title: 'جزئیات درخواست',
    tracking: 'کد پیگیری',
    type: 'نوع درخواست',
    priority: 'اولویت',
    date: 'تاریخ و زمان ثبت',
    location: 'موقعیت و آدرس',
    description: 'شرح درخواست',
    operatorNotes: 'توضیحات اپراتور',
    referralNotes: 'توضیحات گروه ارجاع‌دهنده',
    citizenFiles: 'تصاویر و فایل‌های شهروند',
    start: 'شروع عملیات',
    continueDocs: 'ثبت مستندات',
    docsBefore: 'مستندات قبل از عملیات',
    docsAfter: 'مستندات بعد از عملیات',
    finish: 'ثبت نتیجه نهایی',
    blocked:
      'تا تعیین تکلیف درخواست باز فعلی، پذیرش درخواست جدید برای این خودرو غیرفعال است.',
    alreadyOpen: 'این درخواست در حال انجام است',
  },

  openRequests: {
    title: 'درخواست‌های باز',
    empty: 'درخواست بازی وجود ندارد',
  },

  documents: {
    beforeTitle: 'مستندات قبل از عملیات',
    afterTitle: 'مستندات بعد از عملیات',
    notes: 'توضیحات تکمیلی',
    notesPlaceholder: 'توضیحات مربوط به وضعیت محل را بنویسید...',
    addPhoto: 'عکس از گالری',
    takePhoto: 'عکس با دوربین',
    addVideo: 'فیلم از گالری',
    takeVideo: 'فیلم با دوربین',
    addAudio: 'ضبط صوت',
    stopAudio: 'توقف ضبط',
    save: 'ذخیره و ادامه',
    empty: 'هنوز مستندی ثبت نشده است',
  },

  complete: {
    title: 'ثبت نتیجه نهایی',
    action: 'چه اقدامی انجام شده است؟',
    actionPlaceholder: 'شرح اقدام انجام‌شده',
    outcome: 'نتیجه عملیات',
    outcomePlaceholder: 'نتیجه را توضیح دهید',
    finalNotes: 'توضیحات نهایی',
    finalPlaceholder:
      'توضیح دهید درخواست کامل انجام شده یا علت عدم تکمیل / انصراف چیست.',
    followUp: 'نیاز به اقدام دیگری وجود دارد',
    complete: 'تکمیل و خاتمه',
    incomplete: 'عدم تکمیل و خاتمه',
    cancel: 'انصراف',
    notesRequired: 'ثبت توضیحات نهایی الزامی است.',
    actionRequired: 'ثبت اقدام انجام‌شده الزامی است.',
    outcomeRequired: 'ثبت نتیجه عملیات الزامی است.',
    photosRequired: 'برای تکمیل، حداقل یک عکس قبل و یک عکس بعد از عملیات لازم است.',
    reasonRequired: 'برای عدم تکمیل یا انصراف، ثبت علت الزامی است.',
  },

  notifications: {
    title: 'اعلان‌ها',
    empty: 'اعلانی وجود ندارد',
  },
} as const;
